name: bShortcut
main: com.github.Heliwr.bShortcut.bShortcut
version: 1.3
author: beecub, Waterflames, Heliwr
description: >
             Shortcuts
commands:
  bShortcut:
    description: Reload Command for bShortcut
    usage: |
           /<command> [reload]